version: "3.8"

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    env_file: .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
        echo 'Running migrations...' &&
        npx migrate-mongo up &&
        npm run start:dev
      "

  docs:
    build: .
    container_name: compodoc_server
    restart: "no"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
        npm run compodoc:serve
      "
    ports:
      - "8080:8080"
    depends_on:
      - app
